spring:
  application:
    name: adidas-db-registration-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
